name: Deploy to Yandex Serverless

# 🚀 Запускается при push в production или вручную из UI
on:
  push:
    branches: [ production ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем код
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Авторизуемся в YC CLI
      - name: Authenticate to Yandex Cloud
        uses: yc-actions/cli-authenticate@v1
        with:
          service-account-key: ${{ secrets.YC_SA_KEY }}   # полный JSON-ключ

      # 3. Логинимся в Container Registry
      - name: Docker login to YCR
        run: |
          echo '${{ secrets.YC_SA_KEY }}' \
            | docker login --username oauth --password-stdin '${{ secrets.YC_REGISTRY }}'

      # 4. Сборка и push образа
      - name: Build & push image
        env:
          IMAGE: '${{ secrets.YC_REGISTRY }}/${{ secrets.YC_REPOSITORY }}:${{ github.sha }}'
        run: |
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      # 5. Деплой в Serverless Containers
      - name: Deploy to Serverless Containers
        uses: yc-actions/yc-sls-container-deploy@v2
        with:
          folder-id:      ${{ secrets.YC_FOLDER_ID }}
          container-name: vkPalmAi
          image-url:      '${{ secrets.YC_REGISTRY }}/${{ secrets.YC_REPOSITORY }}:${{ github.sha }}'
          memory:         512   # МБ
          timeout:        30    # сек
