# .github/workflows/deploy.yml
name: Deploy to Yandex Serverless Container

on:
  push:
    branches: [production]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: YC – get IAM token
        id: yc-auth
        uses: yc-actions/yc-iam-token@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_KEY }}

      - name: Docker login to YCR
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: iam
          password: ${{ steps.yc-auth.outputs.token }}

      - name: Build & push image
        env:
          IMAGE: cr.yandex/${{ secrets.YC_REGISTRY }}/${{ secrets.YC_REPOSITORY }}:${{ github.sha }}
        run: |
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Deploy to SLS Container
        uses: yc-actions/yc-sls-container-deploy@v3      # ← главное исправление
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_KEY }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          container-name: vkPalmAi
          revision-image-url: cr.yandex/${{ secrets.YC_REGISTRY }}/${{ secrets.YC_REPOSITORY }}:${{ github.sha }}
          revision-service-account-id: ${{ secrets.YC_SA_ID }}
          revision-memory: 512Mb
          revision-timeout: 30
