name: Deploy to Yandex Serverless Container

on:
  push:
    branches: [production]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Забираем код
      - uses: actions/checkout@v4

      # 2. Получаем IAM-токен из JSON-ключа
      - name: YC – get IAM token
        id: yc-auth
        uses: yc-actions/yc-iam-token@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_KEY }}

      # 3. Логинимся в Container Registry
      - name: Docker login to YCR
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: iam
          password: ${{ steps.yc-auth.outputs.token }}

      # 4. Сборка и пуш образа
      - name: Build & push image
        env:
          IMAGE: cr.yandex/${{ secrets.YC_REGISTRY }}/${{ secrets.YC_REPOSITORY }}:${{ github.sha }}
        run: |
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      # 5. Деплой Serverless-контейнера
      - name: Deploy to SLS Container
        uses: yc-actions/yc-sls-container-deploy@v3
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_KEY }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          container-name: vkpalm-ai                     # ← только lowercase!
          revision-image-url: cr.yandex/${{ secrets.YC_REGISTRY }}/${{ secrets.YC_REPOSITORY }}:${{ github.sha }}
          revision-service-account-id: ${{ secrets.YC_SA_ID }}
          revision-memory: 512Mb
          revision-cores: 1
          revision-core-fraction: 100
          revision-concurrency: 8
          revision-execution-timeout: 30               # сек, поменяй если надо
