name: Deploy to Yandex Serverless

on:
  push:
    branches: [ production ]       # деплой при пуше в production
  workflow_dispatch:               # + кнопка “Run workflow”

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Код репозитория
    - uses: actions/checkout@v4

    # 2. Получаем IAM-токен
    - name: YC – get IAM token
      id: yc-auth
      uses: yc-actions/yc-iam-token@v1        # ← верный namespace
      with:
        service-account-json: ${{ secrets.YC_SA_KEY }}

    # 3. Логин в Container Registry
    - name: Docker login to YCR
      env:
        IAM_TOKEN: ${{ steps.yc-auth.outputs.iam_token }}
      run: echo "$IAM_TOKEN" \
           | docker login --username oauth --password-stdin cr.yandex

    # 4. Сборка и пуш
    - name: Build & push image
      env:
        IMAGE: cr.yandex/${{ secrets.YC_REGISTRY }}/${{ secrets.YC_REPOSITORY }}:${{ github.sha }}
      run: |
        docker build -t "$IMAGE" .
        docker push "$IMAGE"

    # 5. Деплой в SLS Containers
    - name: Deploy to Serverless Container
      uses: yc-actions/yc-sls-container-deploy@v2   # ← верный namespace
      with:
        folder-id:      ${{ secrets.YC_FOLDER_ID }}
        container-name: vkPalmAi
        image-url:      cr.yandex/${{ secrets.YC_REGISTRY }}/${{ secrets.YC_REPOSITORY }}:${{ github.sha }}
        memory:         512       # МБ
        timeout:        30        # сек
