name: Deploy to Yandex Serverless

# 🚀 Триггер либо пуш в production, либо кнопка Run workflow
on:
  push:
    branches: [ production ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Код
      - uses: actions/checkout@v4

      # 2) Авторизация в YC CLI (Новый namespace)
      - name: YC Auth
        uses: yandex-cloud/actions/auth@v0.1
        with:
          service-account-json: ${{ secrets.YC_SA_KEY }}

      # 3) Логин в Container Registry
      - name: Docker login to YCR
        run: echo "${{ secrets.YC_SA_KEY }}" \
             | docker login --username json_key \
               --password-stdin cr.yandex

      # 4) Сборка и пуш
      - name: Build & Push image
        env:
          IMAGE: cr.yandex/${{ secrets.YC_REGISTRY }}/${{ secrets.YC_REPOSITORY }}:${{ github.sha }}
        run: |
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      # 5) Деплой
      - name: Deploy to Serverless Container
        uses: yandex-cloud/actions/sls-container/deploy@v0.1
        with:
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          container-name: vkPalmAi
          image-url: cr.yandex/${{ secrets.YC_REGISTRY }}/${{ secrets.YC_REPOSITORY }}:${{ github.sha }}
          memory: 512
          timeout: 30
